### PR TITLE
Improve Bypass Script to work with many reviews

### PR DESCRIPTION
**Pull request by rubensf**
Fix INF-293

### CODE REVIEW

**Comment by mfeeneybuf** [comment]
ooc, how'd you test this?

**Comment by rubensf** [comment]
> ooc, how'd you test this?

Manually, using a fine grained PAT 😅

**Comment by mfeeneybuf** [comment]
I'm seeing several issues related to `TEMP` and file naming. Wondering if something was lost in the translation from manual testing to .yaml file? I can submit a commit with my changes -- that'll explain it in detail.

**Comment by rubensf** [comment]
> I'm seeing several issues related to TEMP and file naming. Wondering if something was lost in the translation from manual testing to .yaml file? I can submit a commit with my changes -- that'll explain it in detail.

Interesting, I think I wrote it first and then kept copying & pasting to my cmd line to test.

I do mostly use fish shell and test bash using `bash --norc` so it's possible this is egregiously wrong 😓  Feel free to send a commit

**Comment by mfeeneybuf** [comment]
I sent a commit with some changes. I was testing with #6690 and #6558, and I think it looks ok?

We'd probably be well served factoring the `$TEMP/p${i}merge.json` (and friends) into local variables with better names.

**Comment by rubensf** [comment]
And yet again I feel like I'm just a kid playing with bash :')

And yeah, I was testing with 6690 (and a lower per page limit) and it seem to have worked ok!

> We'd probably be well served factoring the $TEMP/p${i}merge.json (and friends) into local variables with better names.

... probably... but I'm hoping this will Just Work (tm) and we won't have to look at this for ages :D

**Review by mfeeneybuf — APPROVED** [review]
Now as a co-author, lgtm :)

**Pull request merged**
